name: Create Release

on:
  push:
    branches: main

permissions:
  contents: write

jobs:
  Release:
    uses: THD-C/GH_Actions/.github/workflows/release.yml@main
    secrets: inherit

  Compile_Proto_Python:
    needs: Release
    uses: THD-C/Protocol/.github/workflows/compile-protobuf.yml@main
    with:
      name: ${{ needs.Release.outputs.version_tag }}
              