name: Create Release

on:
  push:
    branches: main

permissions:
  contents: write

jobs:
  Release:
    uses: THD-C/GH_Actions/.github/workflows/release.yml@main
    with:
      build_docker: false
    secrets: inherit

  Proto_Python:
    needs: Release
    uses: THD-C/Protocol/.github/workflows/compile-protobuf.yml@main
    secrets: inherit
    with:
      version: ${{ needs.Release.outputs.version_tag }}

  Build_Docker_Images:
    runs-on: ubuntu-latest
    needs: Proto_Python
    steps:
      - name: Dispatch event
        shell: pwsh
        run: |
          Invoke-RestMethod -Method Post -Headers @{
            "Accept"               = "application/vnd.github+json"
            "Authorization"        = "Bearer ${{ secrets.THDCPL_TOKEN }}"
            "X-GitHub-Api-Version" = "2022-11-28"
          } -Body (
              @{
                  ref = "main"
              } | ConvertTo-Json
          ) -Uri "https://api.github.com/repos/THD-C/The_THDc_App/actions/workflows/build.yml/dispatches"
            